version: '3'
services:
  backend:
    build: ./ruta-al-backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build: ./ruta-al-frontend
    ports:
      - "80:80"

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PLADI
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d